export const PERMISSIONS = {
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  VIEW_USERS: 'VIEW_USERS',

  CREATE_ROLE: 'CREATE_ROLE',
  UPDATE_ROLE: 'UPDATE_ROLE',
  DELETE_ROLE: 'DELETE_ROLE',
  VIEW_ROLES: 'VIEW_ROLES',

  VIEW_PERMISSIONS: 'VIEW_PERMISSIONS',
  UPDATE_ROLE_PERMISSIONS: 'UPDATE_ROLE_PERMISSIONS',
  
  UPDATE_USER_ROLE: 'UPDATE_USER_ROLE',
  VIEW_PROFILE: 'VIEW_PROFILE',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
};