export const PERMISSIONS = {
  USER_CREATE: 'USER:CREATE',
  USER_UPDATE: 'USER:UPDATE',
  USER_DELETE: 'USER:DELETE',
  USER_VIEW: 'USER:VIEW',
  USER_UPDATE_ROLE: 'USER:UPDATE_ROLE',

  ROLE_CREATE: 'ROLE:CREATE',
  ROLE_UPDATE: 'ROLE:UPDATE',
  ROLE_DELETE: 'ROLE:DELETE',
  ROLE_VIEW: 'ROLE:VIEW',
  ROLE_UPDATE_PERMISSIONS: 'ROLE:UPDATE_PERMISSIONS',

  PERMISSION_VIEW: 'PERMISSION:VIEW',
  
  PROFILE_VIEW: 'PROFILE:VIEW',
  PROFILE_UPDATE: 'PROFILE:UPDATE',
};