export const PERMISSIONS = {
  USER_CREATE: 'USER:CREATE',
  USER_UPDATE: 'USER:UPDATE',
  USER_DELETE: 'USER:DELETE',
  USER_VIEW: 'USER:VIEW',
  USER_UPDATE_ROLE: 'USER:UPDATE_ROLE',
  USER_VIEW_DELETED: 'USER:VIEW_DELETED',
  USER_RESTORE: 'USER:RESTORE',

  ROLE_CREATE: 'ROLE:CREATE',
  ROLE_UPDATE: 'ROLE:UPDATE',
  ROLE_DELETE: 'ROLE:DELETE',
  ROLE_VIEW: 'ROLE:VIEW',
  ROLE_UPDATE_PERMISSIONS: 'ROLE:UPDATE_PERMISSIONS',

  PERMISSION_VIEW: 'PERMISSION:VIEW',
  
  PROFILE_VIEW: 'PROFILE:VIEW',
  PROFILE_UPDATE: 'PROFILE:UPDATE',

  PRODUCT_CREATE: 'PRODUCT:CREATE',
  PRODUCT_UPDATE: 'PRODUCT:UPDATE',
  PRODUCT_CHANGE_STATUS: 'PRODUCT:CHANGE_STATUS',
  PRODUCT_DELETE: 'PRODUCT:DELETE',
  PRODUCT_VIEW: 'PRODUCT:VIEW',

  CUSTOMER_CREATE: 'CUSTOMER:CREATE',
  CUSTOMER_UPDATE: 'CUSTOMER:UPDATE',
  CUSTOMER_DELETE: 'CUSTOMER:DELETE',
  CUSTOMER_VIEW: 'CUSTOMER:VIEW',
  CUSTOMER_VIEW_DELETED: 'CUSTOMER:VIEW_DELETED',
  CUSTOMER_RESTORE: 'CUSTOMER:RESTORE',

  SALE_CREATE: 'SALE:CREATE',
  SALE_VIEW: 'SALE:VIEW',
  SALE_UPDATE: 'SALE:UPDATE',
};